image: node:lts-jessie

pages:
  cache:
    paths:
      - node_modules/

  script:
    - yarn install
    - yarn build
    - mv public public.bak
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
