image: node:lts-jessie

pages:
  cache:
    paths:
      - node_modules/

  script:
    - yarn install
    - yarn build
    - find build
    - ls
  artifacts:
    paths:
      - .
      - build
  only:
    - master
